/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HealthApp`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HealthTipsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MedicationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MentalHealthScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NutritionGuideScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SymptomCheckerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WaterTrackingScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/HealthApp`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HealthTipsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MedicationsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MentalHealthScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/NutritionGuideScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SymptomCheckerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/WaterTrackingScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/HealthApp${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/screens/HealthTipsScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/MedicationsScreen${`?${string}` | `#${string}` | ''}` | `/screens/MentalHealthScreen${`?${string}` | `#${string}` | ''}` | `/screens/NutritionGuideScreen${`?${string}` | `#${string}` | ''}` | `/screens/SymptomCheckerScreen${`?${string}` | `#${string}` | ''}` | `/screens/WaterTrackingScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/HealthApp`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HealthTipsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MedicationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MentalHealthScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NutritionGuideScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SymptomCheckerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/WaterTrackingScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
